# Generated by Django 5.1.2 on 2025-03-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='user_food_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='hydrationlog',
            name='user_hydration_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
