# Generated by Django 5.1.2 on 2025-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log_api', '0003_remove_foodpreference_dairy_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='notes',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
