# Generated by Django 5.1.2 on 2025-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log_api', '0004_remove_foodlog_notes_foodlog_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
