# Generated by Django 5.1.2 on 2025-03-04 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log_api', '0005_foodlog_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationlog',
            name='beverage_type',
            field=models.CharField(choices=[('water', 'Water'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('juice', 'Juice'), ('milk', 'Milk'), ('smoothie', 'Smoothie'), ('soda', 'Soda'), ('sports_drink', 'Sports Drink'), ('other', 'Other')], default='water', max_length=20),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
