# Generated by Django 5.1.2 on 2025-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_log_api', '0006_hydrationlog_beverage_type_alter_hydrationlog_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpreference',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
